### PR TITLE
Remove jQuery as a dependency

### LINKED ISSUE #114: Replace jQuery to decrease weight
jQuery adds quite a bit of weight to the client if you are not already using it. With Angular and React as popular as they are, a number of projects no longer need jQuery.

Can the existing uses of jQuery somehow be replaced with something else?

This project only uses it in the follow lines of code

```
  $(window).on "click keydown", -> monitor(true)

  # catch window blur events when requested and where supported
  # We'll use jQuery here instead of window.blur so that other code can attach blur events:
  # http://stackoverflow.com/q/22415296/586086
  $(window).blur MonitorInternals.onWindowBlur
  $(window).focus MonitorInternals.onWindowFocus
```

### PR DESCRIPTION
**Pull request by merlinpatt**
Fixes #114

### CODE REVIEW

**Comment by mizzao** [comment]
This looks identical to #101 :)

@merlinpatt I'm a bit busy in the middle of transitioning to a new job right now, so I gave you commit access to make any changes you'd like. It would be nice to test all this out using the demo app. If you add additional features, try to follow the style used by the rest of the code and add tests where appropriate.

If you give me your Meteor developer username, I can give you permission to publish new versions of the package to Atmosphere as well.

**Comment by merlinpatt** [comment]
@mizzao Oh wow, didn't even see that. I'll close this one and merge in that one. My Meteor username is also merlinpatt

**Comment by merlinpatt** [comment]
@mizzao I don't seem to have merge privileges for this yet

**Comment by mizzao** [comment]
You have to accept the invitation to collaborate: 

image

Go to https://github.com/mizzao/meteor-user-status/invitations

**Comment by merlinpatt** [comment]
@mizzao I've accepted the invitation and merged the jQuery PR but when I went to publish, I got this message

```
You are not an authorized maintainer for this package.
```

**Comment by mizzao** [comment]
Sorry, I've added you now! I usually use the following simple checklist for publishing, although you can do what works for you:

- [ ] Pick an appropriate version number (e.g. `0.6.6` becomes `0.6.7` or `0.7.0` depending on how much changed)
- [ ] Update the `History.md` file to reflect all changes that will be in the new version. If you've been keeping it up to date, this just involves inserting the above version number below `vNEXT`. Here you may want to mention that it now longer depends on jQuery.
- [ ] Update this version number in `package.json`.
- [ ] `git commit` (but don't push yet).
- [ ] Try `meteor publish`
- [ ] If everything worked, `git tag v0.x.y` and push the tag (`git push origin 0.x.y`; this allows others to find the code for this version) and merge into master and push that too. (If you aren't rebasing a feature branch you may want to merge first before publishing)

Thanks so much for your help!

**Pull request closed without merging**
