### PR TITLE
Remove the need of jquery

### PR DESCRIPTION
**Pull request by hlehmann**

### CODE REVIEW

**Comment by santiq** [comment]
👍

**Comment by mizzao** [comment]
I understand the idea here, but doesn't Meteor include jQuery by default? What will this save?

**Comment by hlehmann** [comment]
Meteor include jQuery by default but only on server side (that's strange...). So if we don't use blaze or jquery it has no reason to get it on the client.

**Comment by jmaguirrei** [comment]
@mizzao Hello, after Meteor release 1.4.3.1, Jquery and Blaze could be removed, if you use, for example, React,

Is it possible to remove now Jquery from this package?

**Comment by mizzao** [comment]
@hlehmann I don't have time to maintain this project anymore, so I gave you commit access to make any changes you'd like. It would be nice to follow the style used by the rest of the code and add some tests for future updates, if appropriate.

If you send me your Meteor username, I can give you permission to publish updates to Atmosphere as well.

**Comment by hlehmann** [comment]
Sorry, I have no more time for this too

**Pull request merged**
